apiVersion: v1
kind: Secret
metadata:
  name: ibm-entitlement-key
  namespace: {{ .Values.default_namespace }}
data:
  .dockerconfigjson: {{ .Values.ibm_entitlement_secret }}
type: kubernetes.io/dockerconfigjson