apiVersion: v1 
kind: Service 
metadata: 
  name: watson-nlp-container
  namespace: {{ .Values.default_namespace }}
spec: 
  type: ClusterIP 
  selector: 
    app: watson-nlp-container 
  ports: 
  - port: 8080 
    protocol: TCP 
    targetPort: 8080